//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolnicaClient.BolnicaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Korisnik", Namespace="http://schemas.datacontract.org/2004/07/BolnicaWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Korisnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProizvodjacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDProizvodjacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKorisnickaGrupaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKorisnickiRacunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OIBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PTTBrojField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proizvodjac {
            get {
                return this.ProizvodjacField;
            }
            set {
                if ((object.ReferenceEquals(this.ProizvodjacField, value) != true)) {
                    this.ProizvodjacField = value;
                    this.RaisePropertyChanged("Proizvodjac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grad {
            get {
                return this.GradField;
            }
            set {
                if ((object.ReferenceEquals(this.GradField, value) != true)) {
                    this.GradField = value;
                    this.RaisePropertyChanged("Grad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupa {
            get {
                return this.GrupaField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupaField, value) != true)) {
                    this.GrupaField = value;
                    this.RaisePropertyChanged("Grupa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDProizvodjac {
            get {
                return this.IDProizvodjacField;
            }
            set {
                if ((this.IDProizvodjacField.Equals(value) != true)) {
                    this.IDProizvodjacField = value;
                    this.RaisePropertyChanged("IDProizvodjac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKorisnickaGrupa {
            get {
                return this.IDKorisnickaGrupaField;
            }
            set {
                if ((this.IDKorisnickaGrupaField.Equals(value) != true)) {
                    this.IDKorisnickaGrupaField = value;
                    this.RaisePropertyChanged("IDKorisnickaGrupa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKorisnickiRacun {
            get {
                return this.IDKorisnickiRacunField;
            }
            set {
                if ((this.IDKorisnickiRacunField.Equals(value) != true)) {
                    this.IDKorisnickiRacunField = value;
                    this.RaisePropertyChanged("IDKorisnickiRacun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OIB {
            get {
                return this.OIBField;
            }
            set {
                if ((object.ReferenceEquals(this.OIBField, value) != true)) {
                    this.OIBField = value;
                    this.RaisePropertyChanged("OIB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PTTBroj {
            get {
                return this.PTTBrojField;
            }
            set {
                if ((object.ReferenceEquals(this.PTTBrojField, value) != true)) {
                    this.PTTBrojField = value;
                    this.RaisePropertyChanged("PTTBroj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupa", Namespace="http://schemas.datacontract.org/2004/07/BolnicaWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Grupa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKorisnickaGrupaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KorisnickaGrupaNazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKorisnickaGrupa {
            get {
                return this.IDKorisnickaGrupaField;
            }
            set {
                if ((this.IDKorisnickaGrupaField.Equals(value) != true)) {
                    this.IDKorisnickaGrupaField = value;
                    this.RaisePropertyChanged("IDKorisnickaGrupa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KorisnickaGrupaNaziv {
            get {
                return this.KorisnickaGrupaNazivField;
            }
            set {
                if ((object.ReferenceEquals(this.KorisnickaGrupaNazivField, value) != true)) {
                    this.KorisnickaGrupaNazivField = value;
                    this.RaisePropertyChanged("KorisnickaGrupaNaziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proizvodjac", Namespace="http://schemas.datacontract.org/2004/07/BolnicaWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Proizvodjac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDProizvodjacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDProizvodjac {
            get {
                return this.IDProizvodjacField;
            }
            set {
                if ((this.IDProizvodjacField.Equals(value) != true)) {
                    this.IDProizvodjacField = value;
                    this.RaisePropertyChanged("IDProizvodjac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacijentDoktor", Namespace="http://schemas.datacontract.org/2004/07/BolnicaWCF.Model")]
    [System.SerializableAttribute()]
    public partial class PacijentDoktor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DoktorKorisnickiRacunIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPacijentDoktorVezaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivPacijentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PacijentKorisnickiRacunIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoktorKorisnickiRacunID {
            get {
                return this.DoktorKorisnickiRacunIDField;
            }
            set {
                if ((this.DoktorKorisnickiRacunIDField.Equals(value) != true)) {
                    this.DoktorKorisnickiRacunIDField = value;
                    this.RaisePropertyChanged("DoktorKorisnickiRacunID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPacijentDoktorVeza {
            get {
                return this.IDPacijentDoktorVezaField;
            }
            set {
                if ((this.IDPacijentDoktorVezaField.Equals(value) != true)) {
                    this.IDPacijentDoktorVezaField = value;
                    this.RaisePropertyChanged("IDPacijentDoktorVeza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivPacijenta {
            get {
                return this.NazivPacijentaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivPacijentaField, value) != true)) {
                    this.NazivPacijentaField = value;
                    this.RaisePropertyChanged("NazivPacijenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PacijentKorisnickiRacunID {
            get {
                return this.PacijentKorisnickiRacunIDField;
            }
            set {
                if ((this.PacijentKorisnickiRacunIDField.Equals(value) != true)) {
                    this.PacijentKorisnickiRacunIDField = value;
                    this.RaisePropertyChanged("PacijentKorisnickiRacunID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doktor", Namespace="http://schemas.datacontract.org/2004/07/BolnicaWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Doktor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKOrisnickiRacunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivDoktoraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKOrisnickiRacun {
            get {
                return this.IDKOrisnickiRacunField;
            }
            set {
                if ((this.IDKOrisnickiRacunField.Equals(value) != true)) {
                    this.IDKOrisnickiRacunField = value;
                    this.RaisePropertyChanged("IDKOrisnickiRacun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivDoktora {
            get {
                return this.NazivDoktoraField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivDoktoraField, value) != true)) {
                    this.NazivDoktoraField = value;
                    this.RaisePropertyChanged("NazivDoktora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pacijent", Namespace="http://schemas.datacontract.org/2004/07/BolnicaWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Pacijent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKOrisnickiRacunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivPacijentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKOrisnickiRacun {
            get {
                return this.IDKOrisnickiRacunField;
            }
            set {
                if ((this.IDKOrisnickiRacunField.Equals(value) != true)) {
                    this.IDKOrisnickiRacunField = value;
                    this.RaisePropertyChanged("IDKOrisnickiRacun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivPacijenta {
            get {
                return this.NazivPacijentaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivPacijentaField, value) != true)) {
                    this.NazivPacijentaField = value;
                    this.RaisePropertyChanged("NazivPacijenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lijek", Namespace="http://schemas.datacontract.org/2004/07/BolnicaWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Lijek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrojOdobrenjaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDLIjekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivLijekaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProizvodjacIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrojOdobrenja {
            get {
                return this.BrojOdobrenjaField;
            }
            set {
                if ((object.ReferenceEquals(this.BrojOdobrenjaField, value) != true)) {
                    this.BrojOdobrenjaField = value;
                    this.RaisePropertyChanged("BrojOdobrenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDLIjek {
            get {
                return this.IDLIjekField;
            }
            set {
                if ((this.IDLIjekField.Equals(value) != true)) {
                    this.IDLIjekField = value;
                    this.RaisePropertyChanged("IDLIjek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivLijeka {
            get {
                return this.NazivLijekaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivLijekaField, value) != true)) {
                    this.NazivLijekaField = value;
                    this.RaisePropertyChanged("NazivLijeka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProizvodjacID {
            get {
                return this.ProizvodjacIDField;
            }
            set {
                if ((this.ProizvodjacIDField.Equals(value) != true)) {
                    this.ProizvodjacIDField = value;
                    this.RaisePropertyChanged("ProizvodjacID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bolest", Namespace="http://schemas.datacontract.org/2004/07/BolnicaWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Bolest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GodinaOtkricaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDBolestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivBolestiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpasnostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpasnostIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GodinaOtkrica {
            get {
                return this.GodinaOtkricaField;
            }
            set {
                if ((this.GodinaOtkricaField.Equals(value) != true)) {
                    this.GodinaOtkricaField = value;
                    this.RaisePropertyChanged("GodinaOtkrica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDBolest {
            get {
                return this.IDBolestField;
            }
            set {
                if ((this.IDBolestField.Equals(value) != true)) {
                    this.IDBolestField = value;
                    this.RaisePropertyChanged("IDBolest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivBolesti {
            get {
                return this.NazivBolestiField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivBolestiField, value) != true)) {
                    this.NazivBolestiField = value;
                    this.RaisePropertyChanged("NazivBolesti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opasnost {
            get {
                return this.OpasnostField;
            }
            set {
                if ((object.ReferenceEquals(this.OpasnostField, value) != true)) {
                    this.OpasnostField = value;
                    this.RaisePropertyChanged("Opasnost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpasnostID {
            get {
                return this.OpasnostIDField;
            }
            set {
                if ((this.OpasnostIDField.Equals(value) != true)) {
                    this.OpasnostIDField = value;
                    this.RaisePropertyChanged("OpasnostID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BolnicaService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginKorisnikProvjera", ReplyAction="http://tempuri.org/IService1/LoginKorisnikProvjeraResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik> LoginKorisnikProvjera(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKorisnik", ReplyAction="http://tempuri.org/IService1/GetKorisnikResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik> GetKorisnik();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddKorisnik", ReplyAction="http://tempuri.org/IService1/AddKorisnikResponse")]
        void AddKorisnik(BolnicaClient.BolnicaService.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateKorisnik", ReplyAction="http://tempuri.org/IService1/UpdateKorisnikResponse")]
        void UpdateKorisnik(BolnicaClient.BolnicaService.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteKorisnik", ReplyAction="http://tempuri.org/IService1/DeleteKorisnikResponse")]
        void DeleteKorisnik(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGrupa", ReplyAction="http://tempuri.org/IService1/GetGrupaResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Grupa> GetGrupa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProizvodjac", ReplyAction="http://tempuri.org/IService1/GetProizvodjacResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Proizvodjac> GetProizvodjac();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPacijentByDoktorID", ReplyAction="http://tempuri.org/IService1/GetPacijentByDoktorIDResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.PacijentDoktor> GetPacijentByDoktorID(int IDDoktor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPacijentDoktorVeza", ReplyAction="http://tempuri.org/IService1/AddPacijentDoktorVezaResponse")]
        void AddPacijentDoktorVeza(BolnicaClient.BolnicaService.PacijentDoktor pd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePacijentDoktorVeza", ReplyAction="http://tempuri.org/IService1/UpdatePacijentDoktorVezaResponse")]
        void UpdatePacijentDoktorVeza(BolnicaClient.BolnicaService.PacijentDoktor pd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePacijentDoktorVeza", ReplyAction="http://tempuri.org/IService1/DeletePacijentDoktorVezaResponse")]
        void DeletePacijentDoktorVeza(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDoktor", ReplyAction="http://tempuri.org/IService1/GetDoktorResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Doktor> GetDoktor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPacijent", ReplyAction="http://tempuri.org/IService1/GetPacijentResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Pacijent> GetPacijent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPacijentByVeza", ReplyAction="http://tempuri.org/IService1/GetPacijentByVezaResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik> GetPacijentByVeza(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProizvodjac", ReplyAction="http://tempuri.org/IService1/AddProizvodjacResponse")]
        void AddProizvodjac(BolnicaClient.BolnicaService.Proizvodjac d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProizvodjac", ReplyAction="http://tempuri.org/IService1/UpdateProizvodjacResponse")]
        void UpdateProizvodjac(BolnicaClient.BolnicaService.Proizvodjac d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProizvodjac", ReplyAction="http://tempuri.org/IService1/DeleteProizvodjacResponse")]
        void DeleteProizvodjac(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLijek", ReplyAction="http://tempuri.org/IService1/GetLijekResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Lijek> GetLijek();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLijek", ReplyAction="http://tempuri.org/IService1/AddLijekResponse")]
        void AddLijek(BolnicaClient.BolnicaService.Lijek l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLijek", ReplyAction="http://tempuri.org/IService1/UpdateLijekResponse")]
        void UpdateLijek(BolnicaClient.BolnicaService.Lijek l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLijek", ReplyAction="http://tempuri.org/IService1/DeleteLijekResponse")]
        void DeleteLijek(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBolest", ReplyAction="http://tempuri.org/IService1/GetBolestResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Bolest> GetBolest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBolest", ReplyAction="http://tempuri.org/IService1/AddBolestResponse")]
        void AddBolest(BolnicaClient.BolnicaService.Bolest b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBolest", ReplyAction="http://tempuri.org/IService1/UpdateBolestResponse")]
        void UpdateBolest(BolnicaClient.BolnicaService.Bolest b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBolest", ReplyAction="http://tempuri.org/IService1/DeleteBolestResponse")]
        void DeleteBolest(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BolnicaClient.BolnicaService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BolnicaClient.BolnicaService.IService1>, BolnicaClient.BolnicaService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik> LoginKorisnikProvjera(string Username, string Password) {
            return base.Channel.LoginKorisnikProvjera(Username, Password);
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik> GetKorisnik() {
            return base.Channel.GetKorisnik();
        }
        
        public void AddKorisnik(BolnicaClient.BolnicaService.Korisnik k) {
            base.Channel.AddKorisnik(k);
        }
        
        public void UpdateKorisnik(BolnicaClient.BolnicaService.Korisnik k) {
            base.Channel.UpdateKorisnik(k);
        }
        
        public void DeleteKorisnik(int id) {
            base.Channel.DeleteKorisnik(id);
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Grupa> GetGrupa() {
            return base.Channel.GetGrupa();
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Proizvodjac> GetProizvodjac() {
            return base.Channel.GetProizvodjac();
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.PacijentDoktor> GetPacijentByDoktorID(int IDDoktor) {
            return base.Channel.GetPacijentByDoktorID(IDDoktor);
        }
        
        public void AddPacijentDoktorVeza(BolnicaClient.BolnicaService.PacijentDoktor pd) {
            base.Channel.AddPacijentDoktorVeza(pd);
        }
        
        public void UpdatePacijentDoktorVeza(BolnicaClient.BolnicaService.PacijentDoktor pd) {
            base.Channel.UpdatePacijentDoktorVeza(pd);
        }
        
        public void DeletePacijentDoktorVeza(int id) {
            base.Channel.DeletePacijentDoktorVeza(id);
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Doktor> GetDoktor() {
            return base.Channel.GetDoktor();
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Pacijent> GetPacijent() {
            return base.Channel.GetPacijent();
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik> GetPacijentByVeza(int id) {
            return base.Channel.GetPacijentByVeza(id);
        }
        
        public void AddProizvodjac(BolnicaClient.BolnicaService.Proizvodjac d) {
            base.Channel.AddProizvodjac(d);
        }
        
        public void UpdateProizvodjac(BolnicaClient.BolnicaService.Proizvodjac d) {
            base.Channel.UpdateProizvodjac(d);
        }
        
        public void DeleteProizvodjac(int id) {
            base.Channel.DeleteProizvodjac(id);
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Lijek> GetLijek() {
            return base.Channel.GetLijek();
        }
        
        public void AddLijek(BolnicaClient.BolnicaService.Lijek l) {
            base.Channel.AddLijek(l);
        }
        
        public void UpdateLijek(BolnicaClient.BolnicaService.Lijek l) {
            base.Channel.UpdateLijek(l);
        }
        
        public void DeleteLijek(int id) {
            base.Channel.DeleteLijek(id);
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Bolest> GetBolest() {
            return base.Channel.GetBolest();
        }
        
        public void AddBolest(BolnicaClient.BolnicaService.Bolest b) {
            base.Channel.AddBolest(b);
        }
        
        public void UpdateBolest(BolnicaClient.BolnicaService.Bolest b) {
            base.Channel.UpdateBolest(b);
        }
        
        public void DeleteBolest(int id) {
            base.Channel.DeleteBolest(id);
        }
    }
}
