//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolnicaClient.BolnicaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Korisnik", Namespace="http://schemas.datacontract.org/2004/07/BolnicaWCF.Model")]
    [System.SerializableAttribute()]
    public partial class Korisnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrzavaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrzavaNazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKorisnickiRacunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKorisnikDetaljiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KorisnickaGrupaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KorisnickaGrupaNazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KorisnickiRacunIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OIBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PTTBrojField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrzavaID {
            get {
                return this.DrzavaIDField;
            }
            set {
                if ((this.DrzavaIDField.Equals(value) != true)) {
                    this.DrzavaIDField = value;
                    this.RaisePropertyChanged("DrzavaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DrzavaNaziv {
            get {
                return this.DrzavaNazivField;
            }
            set {
                if ((object.ReferenceEquals(this.DrzavaNazivField, value) != true)) {
                    this.DrzavaNazivField = value;
                    this.RaisePropertyChanged("DrzavaNaziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKorisnickiRacun {
            get {
                return this.IDKorisnickiRacunField;
            }
            set {
                if ((this.IDKorisnickiRacunField.Equals(value) != true)) {
                    this.IDKorisnickiRacunField = value;
                    this.RaisePropertyChanged("IDKorisnickiRacun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKorisnikDetalji {
            get {
                return this.IDKorisnikDetaljiField;
            }
            set {
                if ((this.IDKorisnikDetaljiField.Equals(value) != true)) {
                    this.IDKorisnikDetaljiField = value;
                    this.RaisePropertyChanged("IDKorisnikDetalji");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KorisnickaGrupaID {
            get {
                return this.KorisnickaGrupaIDField;
            }
            set {
                if ((this.KorisnickaGrupaIDField.Equals(value) != true)) {
                    this.KorisnickaGrupaIDField = value;
                    this.RaisePropertyChanged("KorisnickaGrupaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KorisnickaGrupaNaziv {
            get {
                return this.KorisnickaGrupaNazivField;
            }
            set {
                if ((object.ReferenceEquals(this.KorisnickaGrupaNazivField, value) != true)) {
                    this.KorisnickaGrupaNazivField = value;
                    this.RaisePropertyChanged("KorisnickaGrupaNaziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KorisnickiRacunID {
            get {
                return this.KorisnickiRacunIDField;
            }
            set {
                if ((this.KorisnickiRacunIDField.Equals(value) != true)) {
                    this.KorisnickiRacunIDField = value;
                    this.RaisePropertyChanged("KorisnickiRacunID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginStatus {
            get {
                return this.LoginStatusField;
            }
            set {
                if ((this.LoginStatusField.Equals(value) != true)) {
                    this.LoginStatusField = value;
                    this.RaisePropertyChanged("LoginStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OIB {
            get {
                return this.OIBField;
            }
            set {
                if ((object.ReferenceEquals(this.OIBField, value) != true)) {
                    this.OIBField = value;
                    this.RaisePropertyChanged("OIB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PTTBroj {
            get {
                return this.PTTBrojField;
            }
            set {
                if ((object.ReferenceEquals(this.PTTBrojField, value) != true)) {
                    this.PTTBrojField = value;
                    this.RaisePropertyChanged("PTTBroj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BolnicaService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginKorisnikProvjera", ReplyAction="http://tempuri.org/IService1/LoginKorisnikProvjeraResponse")]
        System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik> LoginKorisnikProvjera(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginKorisnikProvjera", ReplyAction="http://tempuri.org/IService1/LoginKorisnikProvjeraResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik>> LoginKorisnikProvjeraAsync(string Username, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BolnicaClient.BolnicaService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BolnicaClient.BolnicaService.IService1>, BolnicaClient.BolnicaService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik> LoginKorisnikProvjera(string Username, string Password) {
            return base.Channel.LoginKorisnikProvjera(Username, Password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BolnicaClient.BolnicaService.Korisnik>> LoginKorisnikProvjeraAsync(string Username, string Password) {
            return base.Channel.LoginKorisnikProvjeraAsync(Username, Password);
        }
    }
}
